#!/bin/bash


_preflight() {

  CMFKIT_OUTSET_DIR="$( pwd -P )"
  CMFKIT_SOURCE_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

  . $CMFKIT_SOURCE_DIR/mod_common
  . $CMFKIT_SOURCE_DIR/mod_deflist
  . $CMFKIT_SOURCE_DIR/mod_platform
  . $CMFKIT_SOURCE_DIR/mod_readybake
}


_dugout_init() {

  local readonly outsetdir="$( pwd -P )"
  local readonly cmfkitdir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
  local rc

  cd $(mktemp -d) || return 1

  #mkdir -p ./cmfkit_coalesce

  #cp -r ${outsetdir}/* .
  [[ -d ${outsetdir}/.cmfkit ]] && cp -r ${outsetdir}/.cmfkit .

  mkdir -p ./.cmfkit/platform
  mkdir -p ./.cmfkit/scenario
  mkdir -p ./.cmfkit/testbank

  cp -r ${cmfkitdir}/platform/* ./.cmfkit/platform
  cp -r ${cmfkitdir}/scenario/* ./.cmfkit/scenario
  cp -r ${cmfkitdir}/testbank/* ./.cmfkit/testbank

  echo; echo "${PWD}"

  CMFKIT_DUGOUT_DIR="${PWD}/.cmfkit"

  cd - >/dev/null

  #[[ ${OLDPWD} != ${outsetdir} ]] && rm -rf ${OLDPWD}
}


_dugout_demolish() {

  rm -rf $CMFKIT_DUGOUT_DIR
}


_preflight

_dugout_init

# establish list of variables defined in a pre-scope context
_deflist_denote_outset

#[[ -v CMFKIT_PLATFORM              ]] || echo
#[[ -v CMFKIT_SCENARIO              ]] || echo
#[[ -v CMFKIT_READYBAKE_IMAGE_SEED  ]] || echo

CMFKIT_PLATFORM="${CMFKIT_PLATFORM:-unknown}"
CMFKIT_SCENARIO="${CMFKIT_SCENARIO:-basic}"

[[ -n "$CMFKIT_READYBAKE_IMAGE_SEED" ]] \
  && _readybake_isolate_buildpath "$CMFKIT_READYBAKE_IMAGE_SEED"

[[ $CMFKIT_PLATFORM =~ readybake ]] \
  && [[ -z "$CMFKIT_READYBAKE_BUILD_PATH" ]] \
  && _dugout_demolish \
  && _error_fatal "unable to isolate Dockerfile for $CMFKIT_READYBAKE_IMAGE_SEED"

[[ $CMFKIT_PLATFORM =~ readybake ]] && _readybake_yield_image
[[ $CMFKIT_PLATFORM =~ readybake ]]  \
  && [[ -z "$CMFKIT_READYBAKE_IMAGE" ]] \
  && _dugout_demolish \
  && _error_fatal "unable to yield image: ${CMFKIT_READYBAKE_BUILD_PATH##*/}"

[[ $CMFKIT_PLATFORM =~ unknown ]] && _platform_autoselect
[[ $CMFKIT_PLATFORM =~ unknown ]] \
  && _dugout_demolish \
  && _error_fatal "unable to select platform"

[[ $CMFKIT_PLATFORM =~ readybake ]] \
  && _debug "placeholder, readybake execute build"
  # replicate current env inside docker container and execute


[[ ! $CMFKIT_PLATFORM =~ readybake ]] \
  && . $CMFKIT_DUGOUT_DIR/platform/$CMFKIT_PLATFORM/setup \
  && _deflist_accrue_vars

[[ $1 =~ build|test ]] \
  && . $CMFKIT_DUGOUT_DIR/scenario/$CMFKIT_SCENARIO && "__$1" \
    || _error "$1 failure: 'scenario/$CMFKIT_SCENARIO' on '$CMFKIT_PLATFORM'"

[[ -z "$1" ]] \
  && . $CMFKIT_DUGOUT_DIR/scenario/$CMFKIT_SCENARIO \
  && __build \
  && __test


_dugout_demolish




#_readybake_yield_image
#_readybake_buildenv

  # differentiate by:
    # - compute_env:   [ nersc github docker ]
    # - os_type:       [ ubuntu macos ]
    # - mpi_wrapper:   [ openmpi mpich intel ]
    # -


# CMFKIT_READYBAKE_IMAGE_SEED
# CMFKIT_PLATFORM [ autoselect nersc github_vm readybake ]
# CMFKIT_SCENARIO [ all default none zilch ]

# CMFKIT_INTERACTIVE [ yes no ]
