#!/bin/bash


_batchrun() {

  local readonly verb="$1"
  local manifest

  cd ${BASH_SOURCE[0]%/*}

  read manifest <<< $(
    find . -mindepth 2  \
           -maxdepth 2  \
           -type f      \
           -path "./_*/${verb}"
  )

  echo "${manifest}" \
    | xargs -n1 /bin/bash -c 'cd ${1%/*} && ./${1##*/}' _

  cd - >/dev/null
}


_readybake_match_build_path() {

  local readonly base_image="$1"


  echo FROM $base_image

  return 0
}


_readybake_yield_image() {

  echo
}


_readybake_buildenv() {

  local readonly dugout_dir="$1"

  local readonly uniq_id=$(( $RANDOM % 10000 + 40000 ))
  local readonly readybake_image="cmfkit_readybake:latest"

  local container_id

  read container_id <<< $(
    docker create --interactive --tty ${readybake_image}
  )

  [[ -n ${container_id} ]] || return 1

  docker cp ${dugout_dir} ${container_id}
}


_readybake_build() {

  echo
}




CMFKIT_READYBAKE_CONTAINER_ID=''



_init() {

  local readonly uniq_id=$(( $RANDOM % 10000 + 40000 ))

  CMFKIT_${uniq_id}_VARLIST_OUTSET=''
  CMFKIT_${uniq_id}_VARLIST_CMAKE_DEFINITIONS=''
  CMFKIT_${uniq_id}_CMDLINE_CMAKE_DEFINITIONS=''
}


