#!/bin/bash


_batchrun() {

  local readonly verb="$1"
  local manifest

  cd ${BASH_SOURCE[0]%/*}

  read manifest <<< $(
    find . -mindepth 2  \
           -maxdepth 2  \
           -type f      \
           -path "./_*/${verb}"
  )

  echo "${manifest}" \
    | xargs -n1 /bin/bash -c 'cd ${1%/*} && ./${1##*/}' _

  cd - >/dev/null
}


_readybake_isolate_buildpath() {

  local readonly base_image="$1"
  local path_dockerfile
  local match_count
  local rc

  read match_count <<< $(
    grep  --recursive \
          --files-with-matches \
        "^FROM ${base_image}" $CMFKIT_DUGOUT_DIR/platform/readybake* \
      | wc -l
  )

  [[ ${match_count} -eq 1 ]] || return 1

  read path_dockerfile <<< $(
    grep  --recursive \
          --files-with-matches \
        "^FROM ${base_image}" $CMFKIT_DUGOUT_DIR/platform/readybake* \
  )

  CMFKIT_READYBAKE_BUILD_PATH="${path_dockerfile%/*}"
}


_readybake_yield_image() {

  [[ -n "$CMFKIT_READYBAKE_BUILD_PATH" ]] || return 1

  local readonly image_tag="cmfkit-${CMFKIT_READYBAKE_BUILD_PATH##*/}"

  cd $CMFKIT_READYBAKE_BUILD_PATH

  DOCKER_BUILDKIT=1 docker build --tag "${image_tag}" .
  rc="$?"

  cd - >/dev/null

  [[ ${rc} -eq 0 ]] || return 1

  CMFKIT_READYBAKE_IMAGE="${image_tag}:latest"
}


_readybake_buildenv() {

  [[ -n "$CMFKIT_READYBAKE_IMAGE" ]] || return 1
  [[ -n "$CMFKIT_DUGOUT_DIR" ]] || return 1

  local readonly readybake_image="$CMFKIT_READYBAKE_IMAGE"
  local readonly dugout_dir="$CMFKIT_DUGOUT_DIR"

  local container_id

  read container_id <<< $(
    docker create --interactive --tty ${readybake_image}
  )

  [[ -n ${container_id} ]] || return 1

  docker cp ${dugout_dir} ${container_id}

  CMFKIT_READYBAKE_CONTAINER_ID="${container_id}"
}


_readybake_build() {

  echo
}


CMFKIT_READYBAKE_BUILD_PATH=''
CMFKIT_READYBAKE_CONTAINER_ID=''

