#!/bin/bash

_debug_dumpvars() {

  local current_vars

  read current_vars <<< $(
    set 2>/dev/null | while read a
      do [[ $a == *=* ]] || break
        echo -n "${a:+ }${a}"
      done
  )

  echo "${current_vars}" | tr ' ' '\n' | sort
}

_debug() {

  local readonly msg="$1"

  echo "."
  echo "cmfkits >> [Debug] << ${msg}"
  echo "."
}


_error() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "cmfkit >> [Error] << ${msg}"
  echo "."
  echo "."

  return 1
}


_error_fatal() {

  local readonly msg="$1"

  echo "."
  echo "."
  echo "cmfkit >> [Fatal Error] << ${msg}"
  echo "."
  echo "."

  exit 1
}

