#!/bin/bash


__build() {

  # list of CMake definition variables to import from existing environment
  _deflist_uptake_outset CMAKE_BUILD_TYPE

  _deflist_accrue_vars

  # convert the CMake def final roster to CMake cmdline form
  _deflist_render_cmdline

  echo; echo; _debug "print CMake definitions - BEGIN"
  echo; echo $CMFKIT_CMDLINE_CMAKE_DEFINITIONS | tr ' ' '\n'
  echo; echo; _debug "print CMake definitions - END"
  echo; echo

  mkdir -p ./build && cd $_
  cmake $CMFKIT_CMDLINE_CMAKE_DEFINITIONS .. && make
}


__test() {

  echo
}

